# Generated by Django 4.2.3 on 2023-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Roll_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Year_of_join', models.BigIntegerField(null=True)),
                ('Stream', models.CharField(max_length=100, null=True)),
                ('Password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=100, null=True)),
                ('ProjectDescription', models.CharField(max_length=10000, null=True)),
                ('TeamLeader', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamMembers', models.BigIntegerField(null=True)),
                ('ProjectName', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
